### ISSUE TITLE
Stop subscribing random people to your repository

### ISSUE THREAD

**Issue by francisbyrne** [joao801/BattleShip#3]
Hey @joao801, please don't add random people you don't know to your repository. It's annoying to get notifications for a repo I don't care about and I'm sure it's frustrating for other people you've done this to.

**Comment by carlaares** [comment]
+1

**Comment by Schlap** [comment]
+2

**Comment by Alwahsh** [comment]
A small note: your +1s arrives at our mail boxes too :)

**Comment by joao801** [comment]
Ok, sorry for that ;)
I' ve a doubt with gtk+ events within my project and was hoping someone here could give me some help.

I really apologize for any kind of inconvenience,
With the best regards,
joao801

**Comment by frioux** [comment]
I've never done any gtk+, not sure why you thought I could help.  For the others annoyed at getting these notifications, if you have a minute just log into github and click ignore instead of watch at the top.

**Comment by n1trux** [comment]
yes, please stop.

**Comment by filipaskviken** [comment]
+1, please remove.

Bästa hälsningar//Filip
